import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import UserMenu from '@/components/UserMenu'
import SupabaseProvider from "@/components/Auth/SupabaseProvider";
import ProfileChecker from '@/components/Auth/ProfileChecker'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const supabase = createClientComponentClient({ cookies })
  const supabase = createServerComponentClient({ cookies });
  const { data: { session } } = await supabase.auth.getSession()
  // console.log("session",session)
  return (
    <html lang="en">
      <body>
        <header className="bg-white shadow-sm">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
            <h1 className="text-xl font-bold text-gray-900">Task Manager</h1>
            {session ? <UserMenu /> : (
              <div className="space-x-4">
                <a href="/login" className="text-sm font-medium text-gray-500 hover:text-gray-900">
                  Login
                </a>
                <a href="/signup" className="text-sm font-medium text-indigo-600 hover:text-indigo-500">
                  Sign Up
                </a>
              </div>
            )}
          </div>
        </header>
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* {children} */}
          <SupabaseProvider>
            <ProfileChecker />
            {children}
          </SupabaseProvider>
        </main>
      </body>
    </html>
  )
}


// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <SupabaseProvider>
//         {/* <ProfileChecker /> */}
//           {children}
//         </SupabaseProvider>
//       </body>
//     </html>
//   )
// }
